<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Driver DetailsAdAddNPNew PersonFAFrom A_197a56</name>
   <tag></tag>
   <elementGuidId>b9bb8703-a892-446d-b082-afdd32315bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-center-bottom-section']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gw-center-bottom-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gw-center-bottom-section</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f12eb20-0ae2-464d-84c9-57dbe415c8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gw-center-bottom-section</value>
      <webElementGuid>6eae66a5-762b-4e61-b243-80bd71559ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driver DetailsAdAddNPNew PersonFAFrom Address BookReRemoveRMRetrieve MVRReset Customized ColumnsNameLicense #License StateMVR StatusStatus DateDo Not Order MVRGo to Contact NameNameLicense #License #License StateLicense StateMVR StatusMVR StatusStatus DateStatus DateDo Not Order MVRDo Not Order MVRGo to ContactGo to Contact Acct Creation Testing KatalonDXL-123CaliforniaNot Ordered√ CDContact DetailRoRolesAdAddressesMVMotor Vehicle RecordPrimary Named InsuredReset Customized ColumnsPolicy LevelAccount LevelMVR ReportNumber of Accidents   &lt;none>012345 or more      &lt;none>012345 or more   Number of Violations   &lt;none>012345 or more      &lt;none>012345 or more   DriverDate Completed Training Class      Training Class Type   &lt;none>Driver's TrainingMature Driver's Training   Good Student      Yes        No  Year First Licensed Qualifies for a Good Driver Discount      Yes        No  Apply Good Driver Discount?      Yes        No  Excluded?      Yes        No  Do Not Order MVR    Accident/Violation Summary</value>
      <webElementGuid>6ea83890-22a1-43a9-8675-1d163dbcec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-center-bottom-section&quot;)</value>
      <webElementGuid>7d34e5f0-6c31-49df-94ce-3bd7f7c4e81c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gw-center-bottom-section']</value>
      <webElementGuid>e88b563e-fa7d-4a09-bace-b6a2374bfa12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-center-panel']/div[2]</value>
      <webElementGuid>54bc017b-f743-409a-b59d-8add677bfaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::div[1]</value>
      <webElementGuid>976d1940-500a-4c2c-baee-a5457ca9831c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>d67a62ae-a2eb-4545-80c8-9b8c8ba78eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gw-center-bottom-section' and (text() = concat(&quot;Driver DetailsAdAddNPNew PersonFAFrom Address BookReRemoveRMRetrieve MVRReset Customized ColumnsNameLicense #License StateMVR StatusStatus DateDo Not Order MVRGo to Contact NameNameLicense #License #License StateLicense StateMVR StatusMVR StatusStatus DateStatus DateDo Not Order MVRDo Not Order MVRGo to ContactGo to Contact Acct Creation Testing KatalonDXL-123CaliforniaNot Ordered√ CDContact DetailRoRolesAdAddressesMVMotor Vehicle RecordPrimary Named InsuredReset Customized ColumnsPolicy LevelAccount LevelMVR ReportNumber of Accidents   &lt;none>012345 or more      &lt;none>012345 or more   Number of Violations   &lt;none>012345 or more      &lt;none>012345 or more   DriverDate Completed Training Class      Training Class Type   &lt;none>Driver&quot; , &quot;'&quot; , &quot;s TrainingMature Driver&quot; , &quot;'&quot; , &quot;s Training   Good Student      Yes        No  Year First Licensed Qualifies for a Good Driver Discount      Yes        No  Apply Good Driver Discount?      Yes        No  Excluded?      Yes        No  Do Not Order MVR    Accident/Violation Summary&quot;) or . = concat(&quot;Driver DetailsAdAddNPNew PersonFAFrom Address BookReRemoveRMRetrieve MVRReset Customized ColumnsNameLicense #License StateMVR StatusStatus DateDo Not Order MVRGo to Contact NameNameLicense #License #License StateLicense StateMVR StatusMVR StatusStatus DateStatus DateDo Not Order MVRDo Not Order MVRGo to ContactGo to Contact Acct Creation Testing KatalonDXL-123CaliforniaNot Ordered√ CDContact DetailRoRolesAdAddressesMVMotor Vehicle RecordPrimary Named InsuredReset Customized ColumnsPolicy LevelAccount LevelMVR ReportNumber of Accidents   &lt;none>012345 or more      &lt;none>012345 or more   Number of Violations   &lt;none>012345 or more      &lt;none>012345 or more   DriverDate Completed Training Class      Training Class Type   &lt;none>Driver&quot; , &quot;'&quot; , &quot;s TrainingMature Driver&quot; , &quot;'&quot; , &quot;s Training   Good Student      Yes        No  Year First Licensed Qualifies for a Good Driver Discount      Yes        No  Apply Good Driver Discount?      Yes        No  Excluded?      Yes        No  Do Not Order MVR    Accident/Violation Summary&quot;))]</value>
      <webElementGuid>f67160df-897f-4305-a32f-11e75d7bfc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
