<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_C_gw-action--expand-button</name>
   <tag></tag>
   <elementGuidId>235653fa-cc53-4b4c-a350-f62e12b296e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TabBar-ClaimTab > div.gw-action--expand-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TabBar-ClaimTab']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TabBar-ClaimTab > .gw-action--expand-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>608df03c-d35c-465c-a8d9-1689e814198a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--expand-button</value>
      <webElementGuid>94be0dbf-8c81-4a42-9e90-27e1c9b22f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>toggleSubMenu</value>
      <webElementGuid>aed7bcdb-6822-4efa-9241-ad23e2b0b051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fdef8d8b-ba02-4b76-892b-d37e41fdc58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e06c91f-5a7b-4c5d-bdcb-89a447ddcca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar-ClaimTab&quot;)/div[@class=&quot;gw-action--expand-button&quot;]</value>
      <webElementGuid>9fed4ed7-37d5-4063-ac02-72570f77723c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TabBar-ClaimTab']/div[3]</value>
      <webElementGuid>5d3bb90a-f939-4b00-bf7f-61e56f6eb699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::div[3]</value>
      <webElementGuid>929616cd-e96b-4249-8483-95e686c68b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NC'])[1]/preceding::div[2]</value>
      <webElementGuid>48ba9254-95ad-4f34-8926-f46cde157831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Claim'])[1]/preceding::div[4]</value>
      <webElementGuid>5e4f08a1-c73c-4a44-8e79-57c6cafb9787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[3]</value>
      <webElementGuid>39e3dbe5-bee4-4219-b31a-c15df91eeff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
