<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NCNew Claim</name>
   <tag></tag>
   <elementGuidId>3060eb8b-d899-4ea2-9601-545a59bc45ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TabBar-ClaimTab-ClaimTab_FNOLWizard']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;New Claim&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfdba289-a132-4d81-a50c-b165ae5538cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>82e0f6db-d613-4bb0-ac7d-d19fb35cbe89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-hasDivider gw-focus</value>
      <webElementGuid>18efde65-f4c5-481b-99a3-a351dbb1256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02e55ed9-8228-4387-a95b-60cd6876276f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>796a9785-c6b5-4857-885e-2d58ea40e224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:^</value>
      <webElementGuid>59803c1a-47fb-4639-a967-1b2de1b152aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d08468f8-ac3c-4f08-9314-0a55b30368ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NCNew Claim</value>
      <webElementGuid>99a9d62c-b097-476d-ad57-455d1ebe451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar-ClaimTab-ClaimTab_FNOLWizard&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]</value>
      <webElementGuid>4070810d-b10a-436a-9e21-efd23ba8e4c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TabBar-ClaimTab-ClaimTab_FNOLWizard']/div</value>
      <webElementGuid>4cf19a77-8b93-4662-a103-1b7c1fe5751e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::div[7]</value>
      <webElementGuid>ef583006-1f42-4e2f-be66-142380940b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
      <webElementGuid>53b29794-9d78-4948-9a3b-b032fd29a849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NCNew Claim' or . = 'NCNew Claim')]</value>
      <webElementGuid>5d99320a-8081-4ed6-83d3-f72a041d5580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
