<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Login-LoginScreen-LoginDV-password</name>
   <tag></tag>
   <elementGuidId>d46d54d4-290f-4422-901e-344fdaa9fce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Login-LoginScreen-LoginDV-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Login-LoginScreen-LoginDV-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;Login-LoginScreen-LoginDV-password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9866d7e9-3a5e-4198-a325-f725a4cc7a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login-LoginScreen-LoginDV-password</value>
      <webElementGuid>7d2dd3c3-c7c6-47d9-b687-1980551e0b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c11c83d7-a3ad-45c2-9295-b47e84c2dbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-PasswordValueWidget--valueField gw-noTrack gw-focus</value>
      <webElementGuid>a51e5038-a1a9-4e16-b794-b28a7579a393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2374550b-0f9f-4b9e-a33c-fdbf6ac31662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1314799e-9a02-42da-9a3c-962624e71fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>656d2cb0-76de-427e-ab29-80268cb02dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Login-LoginScreen-LoginDV-password&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-PasswordValueWidget--valueField gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>85a3c32e-e23c-445e-8e52-0f92a9f4c764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Login-LoginScreen-LoginDV-password']</value>
      <webElementGuid>cea05017-15a0-4d69-9cb1-ce6803f2270a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Login-LoginScreen-LoginDV-password']/div/input</value>
      <webElementGuid>fd76a913-f523-4d66-bea0-5dd70900046d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>4a901fbd-6f73-442e-a130-1dcd9a111210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Login-LoginScreen-LoginDV-password' and @type = 'password']</value>
      <webElementGuid>be27108a-31ca-4011-9650-e105747b0d50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
