<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Login-LoginScreen-LoginDV-password</name>
   <tag></tag>
   <elementGuidId>99d357f7-7530-446f-9357-c01572f53e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Login-LoginScreen-LoginDV-password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Login-LoginScreen-LoginDV-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;Login-LoginScreen-LoginDV-password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>783c2a7e-1acf-4621-b4e8-3a7be462b154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login-LoginScreen-LoginDV-password</value>
      <webElementGuid>e4c9fa0d-f83e-4ae2-a13d-1a3065b2d6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1db3dbc7-bcb5-4e83-9f93-f4b95e345296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-PasswordValueWidget--valueField gw-noTrack</value>
      <webElementGuid>8026cdd0-811b-418c-97ba-117b1a3969c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ceacd20-5b42-4135-a0d4-db55db512596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a69e9756-2f06-44d2-897a-ea1f234f9e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0582b946-9c85-4522-bb50-04d3ae929d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Login-LoginScreen-LoginDV-password&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-PasswordValueWidget--valueField gw-noTrack&quot;]</value>
      <webElementGuid>43bd25bc-7b1a-4bd2-86ff-1bc3b0443ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Login-LoginScreen-LoginDV-password']</value>
      <webElementGuid>1e62156a-846d-4938-a236-7a17de9ac509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Login-LoginScreen-LoginDV-password']/div/input</value>
      <webElementGuid>17e83b1c-d0c5-483b-86e5-50da30abfe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>af2558dd-ef4a-4f82-9272-c1ca701ecf1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Login-LoginScreen-LoginDV-password' and @type = 'password']</value>
      <webElementGuid>8f9d1539-c591-4bc5-8d4a-2471d20e5d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
