<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_noneAnimalCollision while turning le_e70033</name>
   <tag></tag>
   <elementGuidId>e3f069f5-8db6-443c-83c2-f450e34dbd66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61c872cc-779e-45db-9f66-301fa221651c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause</value>
      <webElementGuid>96af2f74-9dea-4df5-8d29-66085da4c182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5116b126-44d8-4c06-937b-3ba58b01fc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>74e2a3d6-1330-4bec-b5c5-10c34bc4265a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>AnimalCollision while turning leftCollision with bicycleCollision with fixed objectCollision with motor vehicleCollision with other objectCollision with pedestrianCollision with train or busDamage in loading or unloadingFalling or moving objectFireGlass breakageMalicious mischief and vandalismRear-end collisionRiot and civil commotionRolloverTheft Audio or other partsTheft of entire vehicle   </value>
      <webElementGuid>1818cb8a-8817-4559-b047-e6dba9c9b20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>6c2c74ea-299a-48c6-92ff-b641f5f93641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause']</value>
      <webElementGuid>312b6adb-453e-402f-bffb-e82b9d54bbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause']/div/div/select</value>
      <webElementGuid>a2f8e595-8612-45b7-9d28-42613d8b7215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Cause'])[1]/following::select[1]</value>
      <webElementGuid>ff598c00-dbdd-47d7-99e2-5bf55b156e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Date'])[1]/following::select[1]</value>
      <webElementGuid>28dc98cd-6d92-4453-b986-45e8ed641b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident Only?'])[1]/preceding::select[1]</value>
      <webElementGuid>bddb2b1e-4b73-4622-93ff-788e0d5d8a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::select[1]</value>
      <webElementGuid>a59423fa-9626-4672-aa24-90100ae4a175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>43e56e21-c85e-4a71-b2bd-ca34584e3d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause' and (text() = '   &lt;none>AnimalCollision while turning leftCollision with bicycleCollision with fixed objectCollision with motor vehicleCollision with other objectCollision with pedestrianCollision with train or busDamage in loading or unloadingFalling or moving objectFireGlass breakageMalicious mischief and vandalismRear-end collisionRiot and civil commotionRolloverTheft Audio or other partsTheft of entire vehicle   ' or . = '   &lt;none>AnimalCollision while turning leftCollision with bicycleCollision with fixed objectCollision with motor vehicleCollision with other objectCollision with pedestrianCollision with train or busDamage in loading or unloadingFalling or moving objectFireGlass breakageMalicious mischief and vandalismRear-end collisionRiot and civil commotionRolloverTheft Audio or other partsTheft of entire vehicle   ')]</value>
      <webElementGuid>dd403214-853c-478e-a497-10fbacd75f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
