<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Involved Vehicle(s)_FNOLWizard-FullWi_155ead</name>
   <tag></tag>
   <elementGuidId>97b35d11-b691-41e5-8cdc-9bbae8ed89e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2004 Chevrolet Malibu visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b143a20-62c1-416d-a7bf-724b1afb335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox</value>
      <webElementGuid>513e39cc-625e-413c-8b1b-1d9099d0b809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f19fdc8-1804-46f7-a0b9-107e86eb46c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2004 Chevrolet Malibu visibility toggle</value>
      <webElementGuid>79e6b699-4eee-4165-b058-c92c06b8f49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>ed68ea4c-8c98-4a74-9e17-c6562fd927ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>bc0b395d-0aac-4d14-951f-38289f6901ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox']</value>
      <webElementGuid>fff91e68-c7ce-4cd6-b727-352e27732a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox']/div/input</value>
      <webElementGuid>6cbeee73-1d69-49df-a5e6-1df5d56ed2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>c85fa3ad-eb70-46f2-8606-694e9039b3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-RightPanel-FNOLWizard_BasicInfoRightPanelSet-0-InsuredVehicleDV-InsuredVehicleInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>5091b2f0-d0bd-4669-9487-1dce771f06b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
