<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_noneAnimalinsect bitescratchstingBur_836184</name>
   <tag></tag>
   <elementGuidId>ae8a42fd-f8c0-49a7-8f7e-0ad3c781b129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d65a08c-f183-4ae7-af77-e4f288898aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause</value>
      <webElementGuid>5371889c-3a9e-4dd1-9070-7ee80a393909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53fa0113-5700-4c1a-9c3c-0d0bb56e23b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>adad1f54-fb09-4702-b176-80b0aa8bd5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Animal/insect bite/scratch/stingBurglaryEarthquakeExplosionFireGlass breakageHailHurricaneMalicious mischief and vandalismMoldRiot and civil commotionSnow/iceStructural failureWater damageWind   </value>
      <webElementGuid>40baca0c-0b43-413a-a18b-bcad625adf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>90da4f28-8042-4f80-9787-bde88c9d9839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause']</value>
      <webElementGuid>03b97354-2d27-462b-9862-677886b9344c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause']/div/div/select</value>
      <webElementGuid>53b66bb2-012e-459c-924e-00e794285495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Cause'])[1]/following::select[1]</value>
      <webElementGuid>b679058c-3e39-4c01-828a-b8612631351b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Details'])[2]/following::select[1]</value>
      <webElementGuid>3090c992-8a9d-4bfe-bc8c-e501b079eec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catastrophe'])[1]/preceding::select[1]</value>
      <webElementGuid>89487e8c-56d8-4809-b569-1e5e33704764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fault Rating'])[1]/preceding::select[2]</value>
      <webElementGuid>c33c424d-0935-4153-9832-c54b9a67be81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/div/div/select</value>
      <webElementGuid>d949a256-582e-4815-883d-142ae8fa1bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsPanel-FNOLWizard_NewLossDetailsPanelSet-Claim_LossCause' and (text() = '   &lt;none>Animal/insect bite/scratch/stingBurglaryEarthquakeExplosionFireGlass breakageHailHurricaneMalicious mischief and vandalismMoldRiot and civil commotionSnow/iceStructural failureWater damageWind   ' or . = '   &lt;none>Animal/insect bite/scratch/stingBurglaryEarthquakeExplosionFireGlass breakageHailHurricaneMalicious mischief and vandalismMoldRiot and civil commotionSnow/iceStructural failureWater damageWind   ')]</value>
      <webElementGuid>e133f5d5-1078-4de6-ba35-871abf7e6e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
