<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_PA</name>
   <tag></tag>
   <elementGuidId>f1e8fb54-0868-4197-a49d-73a8a742987f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5133ae72-5c3a-4335-979b-5ef74d1979c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission</value>
      <webElementGuid>c232a1b6-d620-432d-865e-1e865a4fd688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>1bb03e1c-9f2b-4e7b-b880-2a7b97da4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>83ddc16f-70b8-4515-bc9c-b6da168a97ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>5b283dcf-ec6e-494b-bf9e-ab5fd3228ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf154572-a6f0-4711-8522-62ea65756587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>50ff305c-90a8-43dc-a000-e4eb328afb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission&quot;)</value>
      <webElementGuid>868cd3fc-c34c-4c3a-9f46-d7f057f4904d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission']</value>
      <webElementGuid>29e05c1f-a114-4893-8c6c-10390c0ba8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-Select']/div/div/div</value>
      <webElementGuid>68aa3679-f7cc-448b-89e2-1ec14b3f70d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[6]/following::div[3]</value>
      <webElementGuid>0665ecf6-00bd-40fb-a841-426f9d667bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Auto'])[1]/preceding::div[1]</value>
      <webElementGuid>84737e6d-74d5-4a5a-89f8-eef6b0cff1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Auto'])[2]/preceding::div[5]</value>
      <webElementGuid>16502652-3b69-43b4-a1cb-75bf517bfea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/div/div</value>
      <webElementGuid>d50b7ec7-411b-49bb-9b4a-7e5608ce61b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>26a45b58-83d0-411d-a3b7-ce9340459026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
