<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No data to display</name>
   <tag></tag>
   <elementGuidId>e3a625c9-6808-4445-b8a0-a88cfc5c349e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gw-ListView--empty-info-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PolicySearch-PolicySearchScreen-DatabasePolicySearchPanelSet-PolicySearch_ResultsLV']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;No data to display&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e44f138-a2d3-423d-8e19-e33ebcb9676a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-ListView--empty-info-cell</value>
      <webElementGuid>b2b10979-7f45-4e8b-81e5-a57965288d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No data to display</value>
      <webElementGuid>76bfbdd1-106e-4a02-af13-9fa1f87e97ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicySearch-PolicySearchScreen-DatabasePolicySearchPanelSet-PolicySearch_ResultsLV&quot;)/div[@class=&quot;gw-ListView--inner gw-ListView--empty&quot;]/div[@class=&quot;gw-ListView--empty-info-row&quot;]/div[@class=&quot;gw-ListView--empty-info-cell&quot;]</value>
      <webElementGuid>e5c55fa6-0cb3-41ff-a473-886d15f316d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolicySearch-PolicySearchScreen-DatabasePolicySearchPanelSet-PolicySearch_ResultsLV']/div/div[3]/div</value>
      <webElementGuid>11440db4-103c-4ff9-9b0f-73ca3503f013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producer'])[5]/following::div[8]</value>
      <webElementGuid>bac39b66-a11b-4b74-8262-6c8c7c156096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producer'])[4]/following::div[15]</value>
      <webElementGuid>84e6504e-ddbf-40ac-82ff-5b747f6abf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No data to display']/parent::*</value>
      <webElementGuid>8d70d0b7-11b3-44bf-910d-d6dff75d071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div/div[3]/div</value>
      <webElementGuid>03f50873-e46c-401e-aa63-3b8ba70f45d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No data to display' or . = 'No data to display')]</value>
      <webElementGuid>0570b53f-0e6a-4bd3-8652-e44d542b8d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
