<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_NewAccount-NewAccountScreen_48f3a6</name>
   <tag></tag>
   <elementGuidId>c5b4eb41-1f3a-4229-9d40-d2eef39601ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0100573-67b2-4947-922d-05f4b633ff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34289691-a1ca-4152-8908-f04c9313c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest</value>
      <webElementGuid>d524f82c-14e4-4c01-a7a4-099af9451f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack</value>
      <webElementGuid>2016b84b-c2ed-48af-9340-6c8494b5085a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d4a42bd4-5332-4197-951f-8d1952133217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>46c8f447-8913-49a4-902d-59a09e9b5add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c0609a5a-1b72-4629-b340-39d3bdff3902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bf50844d-f6b0-45af-b064-714aadda3b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-noTrack&quot;]</value>
      <webElementGuid>679b1084-2928-4600-b189-539eb593fd0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest']</value>
      <webElementGuid>d77b80e0-0e00-4a83-a445-bc3c74553efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest']/div/input</value>
      <webElementGuid>953b9fde-99bb-4b9e-9596-98f352219513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/input</value>
      <webElementGuid>3b952f15-37ff-4528-9a23-6322240704d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastNameTest']</value>
      <webElementGuid>7369eb27-b2bd-453a-a1a3-6610cab81318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
