<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_FNOLWizard-FNOLWizard_PickPolicy_12d4ff</name>
   <tag></tag>
   <elementGuidId>cbf51a60-097c-4040-b689-1650809c093a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5961152-0f48-493f-ac87-bf49823bf912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04718f6e-ab92-4d89-8ede-2db917248b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a58858da-067b-415c-84a9-d1ccb66ca225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected</value>
      <webElementGuid>d8560308-3591-4aac-8b46-3d159feaf3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3dfaa848-a629-4acd-be80-e38ace1f20be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>bf32420a-90de-4732-adfd-197e557d657b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected']</value>
      <webElementGuid>f9362a9b-e211-439c-8a54-075cb17fd5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected']/div/input</value>
      <webElementGuid>c96ddee0-8ca7-4f67-8ee9-0048182bab58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/input</value>
      <webElementGuid>dbedb0c9-4797-4fea-a140-e07d347e14db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'FNOLWizard-FNOLWizard_PickPolicyRiskUnitsScreen-PolicySummaryPropertyLV-0-PropertySelected']</value>
      <webElementGuid>3090b039-c687-4754-900c-04042fd77e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
