<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Organization_gw-click-overlay</name>
   <tag></tag>
   <elementGuidId>83624b8b-e20d-4c06-b8c6-25c009f4b08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gw-click-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-click-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gw-click-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60996e36-9977-47f9-8bc0-4a0211dfde2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-click-overlay gw-disable-click</value>
      <webElementGuid>7310a43d-3e18-434c-b5fe-6ab6a66e59d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gw-click-overlay</value>
      <webElementGuid>6cdca07f-9250-4d1a-aa18-1ab3524b3253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-click-overlay&quot;)</value>
      <webElementGuid>8dcd5088-d54e-4ebd-808d-9da65e220f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gw-click-overlay']</value>
      <webElementGuid>762cd2e0-87c9-4e9d-8846-36bbe423877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='gw-theme--cloud-banff']/body/div[2]</value>
      <webElementGuid>b25ae552-9edb-475e-9386-43cffac0eee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>901416c3-c944-4bc1-a96c-f6e1a9fd004b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gw-click-overlay']</value>
      <webElementGuid>a10eb9fe-a5b1-4ad1-91a5-52eea6b5a2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
