<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_none100-002541 Armstrong (Premier)50_ff92c4</name>
   <tag></tag>
   <elementGuidId>92a9b1d7-7050-4220-9074-37da50e991bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>829b8630-4769-4d12-8481-55b3a70c100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode</value>
      <webElementGuid>a68323c2-cf5d-4e6a-8b2c-3b5064e149c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3908921-8567-41ae-82a4-bb9195d90e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>db228129-05fb-4a1e-b201-92c86cd56944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>100-002541 Armstrong (Premier)501-002542 Armstrong - Los Angeles501-002543 Armstrong - San Diego501-002544 Armstrong - Prof Liab Srvcs501-002545 Armstrong - Employer Srvcs501-002546 Armstrong - Cayman Captive SrvsTest 1    </value>
      <webElementGuid>5dbc36a5-19c9-4d6f-bfca-381f7499f186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>331cd01d-a7e7-4f29-b24a-343e9d468406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode']</value>
      <webElementGuid>0c9caae9-0f62-4499-b46d-c79612f87696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode']/div/div/select</value>
      <webElementGuid>1d1099b8-b3e0-413b-8b51-a10fa6d41b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producer Code'])[1]/following::select[1]</value>
      <webElementGuid>94625c65-cf4e-4369-927b-5d40b71c11df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/following::select[1]</value>
      <webElementGuid>dbb94150-fcd9-4746-b486-92086cace63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[49]/div[2]/div/div/div/select</value>
      <webElementGuid>982d8ce3-b53c-4b63-b16e-595fdaf82a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-ProducerCode' and (text() = '   &lt;none>100-002541 Armstrong (Premier)501-002542 Armstrong - Los Angeles501-002543 Armstrong - San Diego501-002544 Armstrong - Prof Liab Srvcs501-002545 Armstrong - Employer Srvcs501-002546 Armstrong - Cayman Captive SrvsTest 1    ' or . = '   &lt;none>100-002541 Armstrong (Premier)501-002542 Armstrong - Los Angeles501-002543 Armstrong - San Diego501-002544 Armstrong - Prof Liab Srvcs501-002545 Armstrong - Employer Srvcs501-002546 Armstrong - Cayman Captive SrvsTest 1    ')]</value>
      <webElementGuid>346a041f-7694-4cb6-b48c-617a6f10b8d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
