<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>a0a3edd2-3979-46b3-a427-3659ef09c80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb5b54dc-44b4-45cc-8840-2e8617827395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest</value>
      <webElementGuid>66886895-6e63-412d-9919-9b6a8c9ad212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--InputWidget gw-big-button gw-actionable gw-focus</value>
      <webElementGuid>7b9ab9d5-9d5e-49b7-957d-a454ef9b1e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>a58d5276-9f93-4e5d-8d43-546f9a2913e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-shortcut</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest&quot;,&quot;key&quot;:&quot;S&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}</value>
      <webElementGuid>db6658ac-3264-4bb7-8a24-6cdc206c46e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-default</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest&quot;,&quot;key&quot;:&quot;ENTER&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}</value>
      <webElementGuid>9f06ee4d-19b3-41b4-9039-95174253518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>b2e99fb6-0095-4357-b772-c14c79d4526e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5f3804f-943e-4ba0-851e-fdf7e86d5e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e37346c0-4a4f-4c83-94cf-5935c9e91209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest&quot;)</value>
      <webElementGuid>806881b4-b9ee-404b-be64-f0e4104d498f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest']</value>
      <webElementGuid>4a91c0fa-35b0-4301-b773-3c1b42cc9d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-searchBtns']/div[2]/div/div</value>
      <webElementGuid>65f489f4-98ae-46a4-b0d6-4cc7e3314463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account #'])[1]/following::div[9]</value>
      <webElementGuid>4140f010-cba4-4870-ab77-8e165e317684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy #'])[2]/following::div[14]</value>
      <webElementGuid>ba7cdc7a-d017-492f-9c96-2e5bbe78c1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='earch']/parent::*</value>
      <webElementGuid>1d0ccaf1-bd06-4f8f-9e6a-098e4b208c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>96e8d425-ac97-429a-8dcc-bbf5374ca4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'OrganizationSearchPopup-OrganizationSearchPopupScreen-OrganizationSearchDV-SearchAndResetInputSet-SearchLinksInputSet-SearchTest' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>66192203-e22f-4521-ada3-30db4b98f5da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
