<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vacant_gw-click-overlay</name>
   <tag></tag>
   <elementGuidId>fe5a09de-b299-4eea-8d30-ef2b994a7ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gw-click-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-click-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gw-click-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72953ed2-c178-4427-a7b3-87a677344b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-click-overlay gw-disable-click</value>
      <webElementGuid>5cc2343f-5549-4792-9921-4ea46bff1a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gw-click-overlay</value>
      <webElementGuid>16276fb6-7b04-44c5-87bc-920559242027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-click-overlay&quot;)</value>
      <webElementGuid>5d884612-a2de-4680-9cad-2e107f5ca5fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gw-click-overlay']</value>
      <webElementGuid>75f5b3d7-abae-4f42-a67d-0a393f59acb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='gw-theme--cloud-banff']/body/div[2]</value>
      <webElementGuid>05781649-bfbc-48be-acfa-e5b7f2072517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>32e9c8b6-1d69-48ca-9b50-3a5d7790c18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gw-click-overlay']</value>
      <webElementGuid>eb602421-b54e-43f8-8ae2-476757af848a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
