<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Class Code_CPBuildingPopup-D_40b60c</name>
   <tag></tag>
   <elementGuidId>148b418a-5d2c-4168-b91a-85638efcf414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CPBuildingPopup-DetailsDV-ClassCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eef2a0d1-9920-44fa-a14b-4e886347469e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>275912ff-c41c-40de-b4b6-da17b8f9d625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-DetailsDV-ClassCode</value>
      <webElementGuid>84bdc321-1f79-4f88-a5e0-33e1dd083136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-picker-input gw-focus</value>
      <webElementGuid>7916ee8a-9ff9-47a4-9af1-98d5632a42d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77cc3ae2-b955-448f-ace2-8605aba838c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>d853a467-a3ab-417d-a3ca-7df00343b248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>bf8210f5-5839-4fec-9c9e-53c3494bd55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e330e31-0a9f-40e3-9289-946caec6eebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-picker-input gw-focus&quot;]</value>
      <webElementGuid>b4beac25-3d94-42ec-b5e7-c5220fe83480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CPBuildingPopup-DetailsDV-ClassCode']</value>
      <webElementGuid>e8217632-6404-451d-93f9-69798331e485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-DetailsDV-ClassCode']/div/input</value>
      <webElementGuid>3b2195a3-7334-48fc-ba29-1cafaa12d02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>24b8bef2-879f-4a90-8cdc-4d6b17f6a09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CPBuildingPopup-DetailsDV-ClassCode']</value>
      <webElementGuid>755c7dc0-87f0-4094-b145-010153ff8cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
