<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_noneBuilding and Personal PropertyCo_420b6a</name>
   <tag></tag>
   <elementGuidId>7b06b28d-d5fb-42d0-b9b1-dae569b36f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CPBuildingPopup-DetailsDV-CoverageForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c82b26b0-0c5b-42d7-978e-35d84fba887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-DetailsDV-CoverageForm</value>
      <webElementGuid>aeb51e4e-8d3d-45a0-925c-1bbb743f4b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02820542-a5b3-4bcd-be73-72909f9c15b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>f57b6030-98ef-439c-9a9e-46c985c99e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   </value>
      <webElementGuid>7a7e54f6-4576-4f7b-b371-a7208055ea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>a61a46ed-f137-4679-a6ea-c8c6be4ae6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CPBuildingPopup-DetailsDV-CoverageForm']</value>
      <webElementGuid>fa981361-a702-4bc6-9b9c-bb1af821c7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-DetailsDV-CoverageForm']/div/div/select</value>
      <webElementGuid>6bbf503e-5cd7-400e-abc9-13996265c387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Form'])[1]/following::select[1]</value>
      <webElementGuid>ea3ead5f-347a-4c8f-ad92-f30a0def480e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding and Lodging Houses, Rooming Houses, Fraternities and Sororities - Up to 10 Units'])[1]/following::select[1]</value>
      <webElementGuid>df2d1fdc-429b-46df-b023-ad3973bc4bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[2]/preceding::select[1]</value>
      <webElementGuid>9adce6a0-dd64-4a10-b42c-d19acadad66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Type'])[1]/preceding::select[1]</value>
      <webElementGuid>063dd0d3-3043-44c2-8d11-d578281df64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2da9e7ce-5431-407e-b65b-a0aafc88b382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CPBuildingPopup-DetailsDV-CoverageForm' and (text() = '   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   ' or . = '   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   ')]</value>
      <webElementGuid>49bece42-3e2b-411c-956a-4353bf33f4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
